### PR TITLE
Fixed bug new release check

### PR DESCRIPTION
**Pull request by Lu191**

### CODE REVIEW

**Comment by dakk** [comment]
What was the bug?

**Review by AlessandroPaparella — COMMENTED** [review]
We could use Version class from Packaging

**Comment by AlessandroPaparella** [comment]
> What was the bug?

I think is just wrong "arithmetic" for versions... If we use Version class, greater/lower operators should work correctly

**Comment by Lu191** [comment]
> What was the bug?

For example solana installed release was `1.11.1` while latest was `1.10.29` so for how it was before the parsed number were `1111` and `11029` and so `1111 < 11029` returned **`True`** even if the version was older, now with the padding with the 0, all should be fine (`11110` and `11029` and so `11110 < 11029` return **`False`**)

**Comment by Lu191** [comment]
> We could use Version class from Packaging

I didn't know that exists a library for this, we can also use it... even if know all should be fine I guess

**Comment by dakk** [comment]
> Packaging

@AlessandroPaparella  is it in standard library? Btw if it's just two lines of code I prefer @Lu191 implementation. 
We need at least one test case, I'll write it now

**Review by dakk — APPROVED** [review]

**Pull request merged**
